/**
 * Dynamic White-Labeling Utility for SmartRW AI.
 * Translate terms based on the current tenant's active themeMode:
 * - 'rt_rw': Lingkungan Rukun Tetangga (RT) / Rukun Warga (RW)
 * - 'cluster': Cluster / Perumahan Mandiri (Blok / Cluster)
 * - 'apartemen': Apartemen / Kondominium (Unit / Lantai / Gedung)
 */

export function getTranslatedLabel(key: string, themeMode?: string): string {
  const mode = themeMode || "rt_rw";

  const dict: Record<string, Record<string, string>> = {
    rt_rw: {
      "RT": "RT",
      "RW": "RW",
      "RT/RW": "RT/RW",
      "RT atau RW": "RT atau RW",
      "Rukun Tetangga": "Rukun Tetangga",
      "Rukun Warga": "Rukun Warga",
      "Warga": "Warga",
      "Data Warga": "Data Warga",
      "Daftar Warga": "Daftar Warga",
      "Penghuni": "Warga",
      "Kas": "Kas",
      "Kas Warga": "Kas Warga",
      "Kas RT/RW": "Kas RT/RW",
      "Saldo Kas": "Saldo Kas RT/RW",
      "Keuangan": "Keuangan",
      "Iuran": "Iuran",
      "Iuran Kas": "Iuran Kas",
      "Iuran Bulanan": "Iuran Bulanan",
      "Surat": "Surat Pengantar",
      "Surat Pengantar": "Surat Pengantar",
      "Arsip Surat": "Arsip Surat",
      "Permohonan Surat": "Permohonan Surat",
      "Layanan Administrasi": "Layanan Administrasi",
      "Verifikasi Warga": "Verifikasi Warga",
      "ADMIN RT": "ADMIN RT",
      "ADMIN RW": "ADMIN RW",
      "KETUA RT": "KETUA RT",
      "KETUA RW": "KETUA RW",
      "Pengurus": "Pengurus RT/RW",
      "Logo RT/RW": "Logo RT/RW",
      "Sistem RT/RW": "Sistem RT/RW Digital",
      "Wilayah": "Wilayah RT/RW",
      "Nomor RT/RW": "Nomor RT/RW",
      "Alamat (RT/RW)": "Alamat (RT/RW)",
      "Visi Misi": "Visi Misi RT/RW",
    },
    cluster: {
      "RT": "Blok",
      "RW": "Cluster",
      "RT/RW": "Blok/Cluster",
      "RT atau RW": "Blok atau Cluster",
      "Rukun Tetangga": "Blok Hunian",
      "Rukun Warga": "Cluster Perumahan",
      "Warga": "Warga",
      "Data Warga": "Data Warga Cluster",
      "Daftar Warga": "Daftar Warga/Penghuni",
      "Penghuni": "Warga",
      "Kas": "Kas Cluster",
      "Kas Warga": "Kas Cluster",
      "Kas RT/RW": "Dana Kas Cluster",
      "Saldo Kas": "Saldo Kas Cluster",
      "Keuangan": "Kas & Keuangan",
      "Iuran": "Iuran Cluster",
      "Iuran Kas": "Iuran Maintenance/Cluster",
      "Iuran Bulanan": "Iuran Blok/Cluster",
      "Surat": "Izin & Dokumen",
      "Surat Pengantar": "Surat Jalan / Dokumen",
      "Arsip Surat": "Arsip Izin/Dokumen",
      "Permohonan Surat": "Pengajuan Izin/Akses",
      "Layanan Administrasi": "Persetujuan Akses & Izin",
      "Verifikasi Warga": "Verifikasi Warga Baru",
      "ADMIN RT": "ADMIN BLOK",
      "ADMIN RW": "ADMIN CLUSTER",
      "KETUA RT": "KETUA BLOK",
      "KETUA RW": "KETUA CLUSTER",
      "Pengurus": "Pengurus Cluster",
      "Logo RT/RW": "Logo Cluster",
      "Sistem RT/RW": "Manajemen Digital Cluster",
      "Wilayah": "Area Cluster",
      "Nomor RT/RW": "Nomor Blok/Cluster",
      "Alamat (RT/RW)": "Alamat (Blok/Cluster)",
      "Visi Misi": "Visi Misi Cluster",
    },
    apartemen: {
      "RT": "Unit",
      "RW": "Lantai/Gedung",
      "RT/RW": "Unit/Gedung",
      "RT atau RW": "Unit atau Tower/Gedung",
      "Rukun Tetangga": "Nomor Unit",
      "Rukun Warga": "Tower/Lantai Gedung",
      "Warga": "Penghuni",
      "Data Warga": "Data Penghuni",
      "Daftar Warga": "Daftar Penghuni Unit",
      "Penghuni": "Penghuni",
      "Kas": "IPL",
      "Kas Warga": "IPL Gedung",
      "Kas RT/RW": "Iuran IPL & Sinking Fund",
      "Saldo Kas": "Total Dana IPL",
      "Keuangan": "IPL & Finance",
      "Iuran": "Iuran IPL",
      "Iuran Kas": "IPL / Maintenance Fee",
      "Iuran Bulanan": "Service Charge / IPL",
      "Surat": "Izin/Akses Gedung",
      "Surat Pengantar": "Form Izin Masuk/Akses",
      "Arsip Surat": "Arsip Izin/Akses",
      "Permohonan Surat": "Pengisian Form Izin",
      "Layanan Administrasi": "Lobby & Resepsionis",
      "Verifikasi Warga": "Verifikasi Penghuni Unit",
      "ADMIN RT": "ADMIN UNIT",
      "ADMIN RW": "ADMIN TOWER",
      "KETUA RT": "PENGELOLA LANTAI",
      "KETUA RW": "PENGELOLA TOWER",
      "Pengurus": "Building Management",
      "Logo RT/RW": "Logo Gedung/Apartemen",
      "Sistem RT/RW": "Smart Building Systems",
      "Wilayah": "Lantai/Unit",
      "Nomor RT/RW": "Nomor Unit/Lantai",
      "Alamat (RT/RW)": "Alamat Unit/Gedung",
      "Visi Misi": "Visi Misi Pengelola",
    }
  };

  return dict[mode]?.[key] || key;
}
