export const PLAN_FEATURES: Record<string, any> = {
  TRIAL: {
    maxWarga: 50,
    price: "Free",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 50 Warga.",
      "Mading Digital & Struktur Organisasi.",
      "Fitur SOS & Verifikasi Warga.",
      "Layanan Surat Pengantar (Standar).",
      "Modul Keuangan Dasar & PPOB Terintegrasi.",
      "Batas Transaksi Kas: Max 25 per bulan.",
      "AI Chatbot (2x/minggu atau mx 8 chat).",
      "AI Scan Struk (Batas 1x / minggu).",
      "Akses E-Lapak Terbatas (Read Penuh).",
    ],
    keuangan: "DASAR",
    surat: "STANDAR",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 8,
    weeklyAiLimit: 2,
    weeklyScanLimit: 1,
    monthlyTrxLimit: 25,
    multiRT: false,
    posyandu: false,
    bankSampah: false,
    ePemilu: false,
    eLapak: "READ",
    cctv: false,
    sos: true,
    analytics: false,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    booking: false,
    bukuTamu: false,
    inventaris: false,
    complaint: false,
  },
  BASIC: {
    maxWarga: 300,
    price: "Rp 55rb",
    oldPrice: "Rp 85rb",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 300 Warga.",
      "PPOB & Iuran Digital Integrasi",
      "Surat Digital, Keamanan Digital, SOS",
      "Booking Fasum & Kelola Inventaris",
      "AI Scan Struk: Batas 3x / minggu.",
      "AI Chatbot: Batas 15x / minggu.",
      "Batas Transaksi Kas: Max 150 per bulan.",
    ],
    keuangan: "DASAR",
    surat: "STANDAR",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 60,
    weeklyAiLimit: 15,
    weeklyScanLimit: 3,
    monthlyTrxLimit: 150,
    multiRT: false,
    posyandu: false,
    bankSampah: false,
    ePemilu: false,
    eLapak: "FULL",
    cctv: false,
    sos: true,
    analytics: false,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  PRO: {
    maxWarga: 1000,
    price: "Rp 129rb",
    oldPrice: "Rp 169rb",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 1000 Warga.",
      "Modul Posyandu & Bank Sampah",
      "Modul E-Voting (Pemilu Warga)",
      "Laporan Keuangan Full & Custom Surat",
      "AI Scan Struk: Batas 8x / minggu.",
      "AI Chatbot: Batas 50x / minggu.",
      "Batas Transaksi Kas: Max 500 per bulan.",
    ],
    keuangan: "FULL",
    surat: "CUSTOM",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 200,
    weeklyAiLimit: 50,
    weeklyScanLimit: 8,
    monthlyTrxLimit: 500,
    multiRT: false,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    cctv: false,
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  PREMIUM: {
    maxWarga: 1000,
    price: "Rp 239rb",
    oldPrice: "Rp 479rb",
    coreFeatures: [
      "Multi-Tenant RW (5 RT + 1 RW)",
      "Dashboard Konsolidasi Data RW",
      "Integrasi CCTV Keamanan",
      "AI Scan Struk: Batas 125x / minggu.",
      "AI Chatbot: Batas 125x / minggu.",
      "Batas Transaksi Kas: Max 1500 per bulan.",
    ],
    keuangan: "FULL",
    surat: "CUSTOM",
    verifikasi: true,
    chatMode: true,
    ai: true,
    maxAiChats: 500,
    weeklyAiLimit: 125,
    weeklyScanLimit: 125,
    monthlyTrxLimit: 1500,
    multiRT: true,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    cctv: true,
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  ENTERPRISE: {
    maxWarga: 20000,
    price: "Rp 4.5jt",
    oldPrice: "Rp 5.9jt",
    coreFeatures: [
      "Skala Kelurahan/ Perumahan Besar",
      "Custom Domain / White Labeling",
      "AI Strategic & Big Data Insights",
      "Warga & Transaksi Kas Tanpa Batas (Unlimited)",
      "AI Chatbot & Scan Tanpa Batas (Unlimited)",
      "Dedicated CS Manager 24/7",
    ],
    keuangan: "ENTERPRISE",
    surat: "DYNAMIC",
    verifikasi: true,
    chatMode: true,
    ai: true,
    maxAiChats: -1,
    weeklyAiLimit: 9999,
    weeklyScanLimit: 9999,
    monthlyTrxLimit: 999999,
    multiRT: true,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    cctv: true,
    sos: true,
    analytics: true,
    multiRegion: true,
    governance: "HIGH",
    predictiveAI: true,
    inventaris: true,
    booking: true,
    bukuTamu: true,
  },
  EXPIRED: {
    maxWarga: 0,
    price: "Expired",
    coreFeatures: ["Masa trial berakhir. Silakan upgrade paket."],
    keuangan: "NONE",
    surat: "NONE",
    verifikasi: false,
    chatMode: false,
    ai: false,
    isExpired: true,
  },
};

export const PLAN_ALIASES: Record<string, string> = {
  ACTIVE: "TRIAL",
  FREE: "TRIAL",
  STARTER: "TRIAL",
  LITE: "BASIC",
  RT: "BASIC",
  FLASH: "BASIC",
  RW: "PRO",
  GOLD: "PREMIUM",
  DIAMOND: "ENTERPRISE",
  PRIME: "ENTERPRISE",
  GOV: "ENTERPRISE",
  EXPIRED: "EXPIRED",
};

export const PLAN_CONFIG = {
  STARTER: { 
    id: 'starter', 
    name: 'STARTER', 
    focus: 'GRATIS / TRIAL', 
    priceMonthly: 0, 
    priceYearly: 0, 
    features: [
      'Maksimal hingga 50 Warga', 
      'Mading & Struktur Organisasi',
      'Fitur SOS & Verifikasi Warga', 
      'Surat Pengantar & Template Standar', 
      'Modul Keuangan Dasar & PPOB Terintegrasi',
      'Batas 25 Transaksi Kas/Bln',
      'AI Chatbot (2x/minggu max 8 chat)',
      'AI Scan Struk (1x/Minggu)',
      'Akses E-Lapak Terbatas (READ)'
    ], 
    systemKey: 'TRIAL' 
  },
  FLASH: { 
    id: 'flash', 
    name: 'FLASH', 
    focus: 'KHUSUS RT', 
    priceMonthly: 55000, 
    priceOldMonthly: 85000, 
    priceYearly: 550000, 
    features: [
      'Maksimal 300 Warga', 
      'Iuran Digital & PPOB', 
      'Surat Digital & Keuangan', 
      'Booking Fasum & SOS',
      'Kelola Inventaris',
      'AI Scan Struk (3x/Minggu)',
      'AI Chatbot (15x/Minggu)',
      'Batas 150 Transaksi Kas/Bln'
    ], 
    systemKey: 'BASIC' 
  },
  PRO: { 
    id: 'pro', 
    name: 'PRO', 
    focus: 'KHUSUS RW', 
    priceMonthly: 129000, 
    priceOldMonthly: 169000, 
    priceYearly: 1290000, 
    features: [
      'Maksimal 1000 Warga', 
      'Mading & Struktur Organisasi', 
      'Modul Posyandu & Bank Sampah', 
      'Modul E-Voting (Pemilu)', 
      'AI Scan Struk (8x/Minggu)',
      'AI Chatbot (50x/Minggu)',
      'Batas 500 Transaksi Kas/Bln'
    ], 
    systemKey: 'PRO' 
  },
  PREMIUM: { 
    id: 'premium', 
    name: 'PREMIUM', 
    focus: 'MULTI-TENANT RW', 
    priceMonthly: 239000, 
    priceOldMonthly: 479000, 
    priceYearly: 2390000, 
    features: [
      'Available 6 Tenant (RW + 5 RT)', 
      'Dashboard Konsolidasi RW', 
      'Integrasi CCTV Keamanan', 
      'AI Scan Struk (125x/Minggu)',
      'AI Chatbot (125x/Minggu)',
      'Batas 1500 Transaksi Kas/Bln',
      'Layanan Support Prioritas'
    ], 
    systemKey: 'PREMIUM', 
    isBestSeller: true 
  },
  ENTERPRISE: { 
    id: 'enterprise', 
    name: 'ENTERPRISE', 
    focus: 'PERUMAHAN BESAR', 
    priceMonthly: 4500000, 
    priceOldMonthly: 5900000, 
    priceYearly: 25000000, 
    features: [
      'Skala Kelurahan/Besar', 
      'Custom Domain / White Label', 
      'AI Strategic Insights', 
      'Warga & Transaksi UNLIMITED',
      'AI Chatbot & Scan UNLIMITED',
      'Dedicated CS 24/7'
    ], 
    systemKey: 'ENTERPRISE' 
  },
};

export const ADDON_CONFIG = {
  AI_CHAT: { id: 'addon_ai', name: 'Extra AI Chat (100 chats) - 49k/ bln', hpp: 20000, priceMonthly: 49000, featureKey: 'extraAi_100' },
  POSYANDU: { id: 'addon_posyandu', name: 'Modul Kesehatan (Posyandu) - 35k/ bln', hpp: 15000, priceMonthly: 35000, featureKey: 'posyandu' },
  EVOTING: { id: 'addon_evoting', name: 'Modul E-Voting & Pemilu - 45k/ bln', hpp: 20000, priceMonthly: 45000, featureKey: 'ePemilu' },
  BANK_SAMPAH: { id: 'addon_banksampah', name: 'Modul Bank Sampah - 35k/ bln', hpp: 15000, priceMonthly: 35000, featureKey: 'bankSampah' },
  CCTV: { id: 'addon_cctv', name: 'CCTV Integration - 80k/ bln', hpp: 35000, priceMonthly: 80000, featureKey: 'cctv' },
  ELAPAK: { id: 'addon_elapak', name: 'E-Lapak (Pasar Warga) - 50k/ bln', hpp: 20000, priceMonthly: 50000, featureKey: 'eLapakFull' },
  PPOB: { id: 'addon_ppob', name: 'Modul PPOB (Payment Point Online Bank) - 50k/ bln', hpp: 20000, priceMonthly: 50000, featureKey: 'ppob' },
  BOOKING: { id: 'addon_booking', name: 'Modul Booking Fasilitas - 5k/ bln', hpp: 2000, priceMonthly: 5000, featureKey: 'booking' },
  JUMLAH_WARGA_100: { id: 'addon_warga_100', name: 'Ekstra +100 Warga - 15k/ bln', hpp: 5000, priceMonthly: 15000, featureKey: 'warga_100' },
  JUMLAH_WARGA_500: { id: 'addon_warga_500', name: 'Ekstra +500 Warga - 50k/ bln', hpp: 20000, priceMonthly: 50000, featureKey: 'warga_500' },
  SOS: { id: 'addon_sos', name: 'Modul SOS - 29k/ bln', hpp: 10000, priceMonthly: 29000, featureKey: 'modulSos' },
  BUKU_TAMU: { id: 'addon_buku_tamu', name: 'Keamanan Digital - 19k/ bln', priceMonthly: 19000, featureKey: 'bukuTamu' },
  INVENTARIS: { id: 'addon_inventaris', name: 'Modul Inventaris - 15k/ bln', priceMonthly: 15000, featureKey: 'inventaris' },
  AI_AGENT: { id: 'addon_ai_agent', name: 'AI Agent (Asisten 24/7) - 59k/ bln', priceMonthly: 59000, featureKey: 'aiAgent' },
  GRUP_CHAT: { id: 'addon_grup_chat', name: 'Grup Chat Warga - 25k/ bln', priceMonthly: 25000, featureKey: 'grupChat' },
  KELUHAN: { id: 'addon_keluhan', name: 'Lapor Keluhan (Warga)', priceMonthly: 0, featureKey: 'complaint' },
};
