export const PLAN_FEATURES: Record<string, any> = {
  TRIAL: {
    maxWarga: 50,
    price: "Free",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 50 Warga.",
      "Fitur Mading Digital: Kelola pengumuman dan informasi warga secara digital.",
      "Struktur Organisasi: Menampilkan bagan pengurus RT/RW yang rapi.",
      "Layanan Surat Pengantar: Cetak surat pengantar secara otomatis dalam hitungan detik.",
      "Batas Warga: Maksimal 50 Warga.",
      "AI Chatbot: Maksimal 2x Chat / minggu (setara ~8x sebulan, diatur per minggu untuk menghindari spam massal).",
      "AI Scan Struk: Maksimal 1x Scan / minggu (setara ~4x sebulan).",
      "Pencatatan Transaksi: Batas 25 Transaksi Kas / bulan (sangat aman untuk lingkungan kecil yang sedang uji coba).",
      "Fitur PPOB (Bagi-Hasil): Fasilitas pembayaran tagihan (Listrik, PDAM, dll) yang hasilnya bisa menjadi pemasukan Kas RT.",
      "AI Scan Struk (Trial): Fitur unggulan AI untuk memindai foto struk/nota belanja menjadi laporan keuangan otomatis (Batas 3x per bulan).",
      "AI Chatbot: Akses asisten pintar untuk tanya jawab (Batas 5x per bulan).",
      "Sistem SOS: Tombol darurat untuk keamanan lingkungan.",
      "Verifikasi Warga: Sistem verifikasi data pendaftaran warga baru.",
      "Modul Keuangan Dasar: Pencatatan kas sederhana.",
      "Modul Surat Standar: Template surat pengantar standar RT/RW."
    ],
    keuangan: "DASAR",
    surat: "STANDAR",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 8,
    weeklyAiLimit: 8,
    weeklyScanLimit: 1,
    monthlyTrxLimit: 25,
    maxSipil: 5,
    multiRT: false,
    posyandu: false,
    bankSampah: false,
    ePemilu: false,
    eLapak: "READ",
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    booking: false,
    bukuTamu: false,
    inventaris: false,
    complaint: false,
  },
  BASIC: {
    maxWarga: 300,
    price: "Rp 55rb",
    oldPrice: "Rp 85rb",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 300 Warga.",
      "Surat Digital & Layanan Sipil Batas 20 Laporan.",
      "Booking Fasum & Kelola Inventaris",
      "AI Scan Struk: Batas 3x / minggu.",
      "AI Chatbot: Batas 15x / minggu.",
      "Batas Transaksi Kas: Max 150 per bulan.",
    ],
    keuangan: "DASAR",
    surat: "STANDAR",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 60,
    weeklyAiLimit: 15,
    weeklyScanLimit: 3,
    monthlyTrxLimit: 150,
    maxSipil: 20,
    multiRT: false,
    posyandu: false,
    bankSampah: false,
    ePemilu: false,
    eLapak: "FULL",
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  PRO: {
    maxWarga: 1000,
    price: "Rp 129rb",
    oldPrice: "Rp 169rb",
    coreFeatures: [
      "Kapasitas Warga: Maksimal hingga 1000 Warga.",
      "Modul Posyandu & Bank Sampah",
      "Modul E-Voting (Pemilu Warga)",
      "Laporan Keuangan Full & Layanan Sipil Batas 100",
      "AI Scan Struk: Batas 8x / minggu.",
      "AI Chatbot: Batas 50x / minggu.",
      "Batas Transaksi Kas: Max 500 per bulan.",
    ],
    keuangan: "FULL",
    surat: "CUSTOM",
    verifikasi: true,
    chatMode: false,
    ai: true,
    maxAiChats: 200,
    weeklyAiLimit: 50,
    weeklyScanLimit: 8,
    monthlyTrxLimit: 500,
    maxSipil: 100,
    multiRT: false,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  PREMIUM: {
    maxWarga: 1000,
    price: "Rp 239rb",
    oldPrice: "Rp 479rb",
    coreFeatures: [
      "Multi-Tenant RW (5 RT + 1 RW)",
      "Dashboard Konsolidasi Data RW",
      "AI Scan Struk: Batas 125x / minggu.",
      "AI Chatbot: Batas 125x / minggu.",
      "Layanan Sipil Batas 250 Laporan",
      "Batas Transaksi Kas: Max 1500 per bulan.",
    ],
    keuangan: "FULL",
    surat: "CUSTOM",
    verifikasi: true,
    chatMode: true,
    ai: true,
    maxAiChats: 500,
    weeklyAiLimit: 125,
    weeklyScanLimit: 125,
    monthlyTrxLimit: 1500,
    maxSipil: 250,
    multiRT: true,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    sos: true,
    analytics: true,
    multiRegion: false,
    governance: "LOW",
    predictiveAI: false,
    inventaris: true,
    booking: true,
    bukuTamu: true,
    complaint: true,
  },
  ENTERPRISE: {
    maxWarga: 20000,
    price: "Rp 4.5jt",
    oldPrice: "Rp 5.9jt",
    coreFeatures: [
      "Kapasitas Warga: UNLIMITED",
      "Pencatatan Transaksi: UNLIMITED",
      "AI Scan Struk: UNLIMITED",
      "AI Chatbot: UNLIMITED",
      "Skala Kelurahan/ Perumahan Besar",
      "Custom Domain / White Labeling",
      "AI Strategic & Big Data Insights",
      "Warga & Layanan Sipil Tanpa Batas (Unlimited)",
      "AI Chatbot & Scan Tanpa Batas (Unlimited)",
      "Dedicated CS Manager 24/7",
      "Mading Digital: Maksimal 10 gambar per bulan.",
      "ANALYTICS AI: Maksimal 10 x per bulan."
    ],
    keuangan: "ENTERPRISE",
    surat: "DYNAMIC",
    verifikasi: true,
    chatMode: true,
    ai: true,
    maxAiChats: -1,
    weeklyAiLimit: 9999,
    weeklyScanLimit: 9999,
    monthlyTrxLimit: 999999,
    maxSipil: -1,
    multiRT: true,
    posyandu: true,
    bankSampah: true,
    ePemilu: true,
    eLapak: "FULL",
    sos: true,
    analytics: true,
    multiRegion: true,
    governance: "HIGH",
    predictiveAI: true,
    inventaris: true,
    booking: true,
    bukuTamu: true,
  },
  EXPIRED: {
    maxWarga: 0,
    price: "Expired",
    coreFeatures: ["Masa trial berakhir. Silakan upgrade paket."],
    keuangan: "NONE",
    surat: "NONE",
    verifikasi: false,
    chatMode: false,
    ai: false,
    maxSipil: 0,
    isExpired: true,
  },
};

export const PLAN_ALIASES: Record<string, string> = {
  ACTIVE: "TRIAL",
  FREE: "TRIAL",
  STARTER: "TRIAL",
  LITE: "BASIC",
  RT: "BASIC",
  FLASH: "BASIC",
  RW: "PRO",
  GOLD: "PREMIUM",
  DIAMOND: "ENTERPRISE",
  PRIME: "ENTERPRISE",
  GOV: "ENTERPRISE",
  EXPIRED: "EXPIRED",
};

export const PLAN_CONFIG = {
  STARTER: { 
    id: 'starter', 
    name: 'STARTER', 
    focus: 'GRATIS / TRIAL', 
    priceMonthly: 0, 
    priceYearly: 0, 
    features: [
      "Kapasitas Warga: Maksimal hingga 50 Warga.",
      "Fitur Mading Digital: Kelola pengumuman dan informasi warga secara digital.",
      "Struktur Organisasi: Menampilkan bagan pengurus RT/RW yang rapi.",
      "Layanan Surat Pengantar: Cetak surat pengantar secara otomatis dalam hitungan detik.",
      "Batas Warga: Maksimal 50 Warga.",
      "AI Chatbot: Maksimal 2x Chat / minggu (setara ~8x sebulan, diatur per minggu untuk menghindari spam massal).",
      "AI Scan Struk: Maksimal 1x Scan / minggu (setara ~4x sebulan).",
      "Pencatatan Transaksi: Batas 25 Transaksi Kas / bulan (sangat aman untuk lingkungan kecil yang sedang uji coba).",
      "AI Scan Struk (Trial): Fitur unggulan AI untuk memindai foto struk/nota belanja menjadi laporan keuangan otomatis (Batas 3x per bulan).",
      "AI Chatbot: Akses asisten pintar untuk tanya jawab (Batas 5x per bulan).",
      "Sistem SOS: Tombol darurat untuk keamanan lingkungan.",
      "Verifikasi Warga: Sistem verifikasi data pendaftaran warga baru.",
      "Modul Keuangan Dasar: Pencatatan kas sederhana.",
      "Modul Surat Standar: Template surat pengantar standar RT/RW."
    ], 
    systemKey: 'TRIAL' 
  },
  FLASH: { 
    id: 'flash', 
    name: 'FLASH', 
    focus: 'KHUSUS RT', 
    priceMonthly: 55000, 
    priceOldMonthly: 85000, 
    priceYearly: 550000, 
    features: [
      "Kapasitas Warga: Maksimal hingga 300 Warga.",
      "Iuran Digital: Integrasi pembayaran iuran warga secara digital.\n      NB : Bukan bagian dari paket (Kemitraan 50:50)",
      "Surat Digital & Keuangan: Manajemen surat menyurat digital dan pencatatan modul keuangan dasar.",
      "Booking Fasum: Fitur peminjaman fasilitas umum (lapangan, balai warga, dll).",
      "Keamanan Digital & SOS: Fitur tombol darurat (SOS) untuk keamanan lingkungan.",
      "Kelola Inventaris: Pendataan barang milik RT secara digital.",
      "AI Chatbot: Akses asisten pintar hingga 50x per bulan.",
      "AI Chatbot: Maksimal 15x Chat / minggu (setara ~60x sebulan).",
      "AI Scan Struk: Hadir sebagai fitur baru dengan batas 3x Scan / minggu (setara ~12x sebulan).",
      "Pencatatan Transaksi: Batas 150 Transaksi Kas / bulan (setara 5 entry transaksi per hari).",
      "Mading Digital: Maksimal 3 gambar per bulan.",
      "Analitik AI: Maksimal 3 x per bulan."
    ], 
    systemKey: 'BASIC' 
  },
  PRO: { 
    id: 'pro', 
    name: 'PRO', 
    focus: 'KHUSUS RW', 
    priceMonthly: 129000, 
    priceOldMonthly: 169000, 
    priceYearly: 1290000, 
    features: [
      "Kapasitas Warga: Maksimal hingga 1000 Warga.",
      "Modul Posyandu & Bank Sampah: Sistem manajemen kesehatan warga dan pengelolaan sampah lingkungan yang terintegrasi.",
      "Modul E-Voting (Pemilu Warga): Fasilitas pemungutan suara secara digital yang aman dan transparan untuk pemilihan ketua atau kebijakan warga.",
      "Laporan Keuangan Full: Pencatatan serta pelaporan kas yang lebih detail dan komprehensif.",
      "Custom Surat: Fleksibilitas dalam mengubah atau menyesuaikan template surat pengantar sesuai kebutuhan spesifik RW.",
      "AI Chatbot: Akses asisten pintar hingga 50x Chat / minggu (setara ~200x/bln).",
      "AI Scan Struk: Hadir dengan batas 8x Scan / minggu (setara ~32x sebulan).",
      "Pencatatan Transaksi: Batas 500 Transaksi Kas / bulan (setara 15 entry transaksi harian).",
      "Mading Digital: Maksimal 4 gambar per bulan.",
      "Analitik AI: Maksimal 4 x per bulan."
    ], 
    systemKey: 'PRO' 
  },
  PREMIUM: { 
    id: 'premium', 
    name: 'PREMIUM', 
    focus: 'MULTI-TENANT RW', 
    priceMonthly: 239000, 
    priceOldMonthly: 479000, 
    priceYearly: 2390000, 
    features: [
      "Multi-Tenant RW: Mendapatkan 6 Tenant dalam satu akun (1 RW Utama + 5 RT).",
      "Dashboard Konsolidasi RW: Pantau laporan keamanan, keuangan, dan data warga dari seluruh RT secara terpusat dalam satu layar.",
      "Integrasi CCTV Keamanan: Kemampuan integrasi langsung ke sistem CCTV lingkungan untuk pemantauan Real-time di aplikasi.",
      "AI Chatbot & Scan Struk: Maksimal 125x Chat & Scan / minggu (setara ~500x/bln).",
      "AI Scan Struk: Kapasitas pengolahan laporan keuangan otomatis berbasis foto struk (500x per bulan).",
      "Pencatatan Transaksi: Batas 1.500 Transaksi Kas / bulan (setara 50 entry transaksi harian).",
      "Layanan Support Prioritas: Jalur khusus untuk bantuan teknis dan pendampingan implementasi bagi pengurus.",
      "Mading Digital: Maksimal 5 gambar per bulan.",
      "Analitik AI: Maksimal 5 x per bulan."
    ], 
    systemKey: 'PREMIUM', 
    isBestSeller: true 
  },
  ENTERPRISE: { 
    id: 'enterprise', 
    name: 'ENTERPRISE', 
    focus: 'PERUMAHAN BESAR', 
    priceMonthly: 4500000, 
    priceOldMonthly: 5900000, 
    priceYearly: 25000000, 
    features: [
      'Skala Kelurahan/Besar', 
      'Custom Domain / White Label', 
      'Warga & Layanan Sipil UNLIMITED',
      'AI Chatbot & Scan UNLIMITED',
      'Dedicated CS 24/7',
      'Mading Digital: Maksimal 10 gambar per bulan.',
      'ANALYTICS AI: Maksimal 10 x per bulan.'
    ], 
    systemKey: 'ENTERPRISE' 
  },
};

export const ADDON_CONFIG = {
  AI_CHAT: { id: 'addon_ai', name: 'Extra AI Chat (100 chats) - 49k/ bln', hpp: 20000, priceMonthly: 49000, featureKey: 'extraAi_100' },
  POSYANDU: { id: 'addon_posyandu', name: 'Modul Kesehatan (Posyandu) - 35k/ bln', hpp: 15000, priceMonthly: 35000, featureKey: 'posyandu' },
  EVOTING: { id: 'addon_evoting', name: 'Modul E-Voting & Pemilu - 45k/ bln', hpp: 20000, priceMonthly: 45000, featureKey: 'ePemilu' },
  BANK_SAMPAH: { id: 'addon_banksampah', name: 'Modul Bank Sampah - 35k/ bln', hpp: 15000, priceMonthly: 35000, featureKey: 'bankSampah' },
  ELAPAK: { id: 'addon_elapak', name: 'E-Lapak (Pasar Warga) - 50k/ bln', hpp: 20000, priceMonthly: 50000, featureKey: 'eLapakFull' },
  BOOKING: { id: 'addon_booking', name: 'Modul Booking Fasilitas - 5k/ bln', hpp: 2000, priceMonthly: 5000, featureKey: 'booking' },
  JUMLAH_WARGA_100: { id: 'addon_warga_100', name: 'Ekstra +100 Warga - 15k/ bln', hpp: 5000, priceMonthly: 15000, featureKey: 'warga_100' },
  JUMLAH_WARGA_500: { id: 'addon_warga_500', name: 'Ekstra +500 Warga - 50k/ bln', hpp: 20000, priceMonthly: 50000, featureKey: 'warga_500' },
  SOS: { id: 'addon_sos', name: 'Modul SOS - 29k/ bln', hpp: 10000, priceMonthly: 29000, featureKey: 'modulSos' },
  BUKU_TAMU: { id: 'addon_buku_tamu', name: 'Keamanan Digital - 19k/ bln', priceMonthly: 19000, featureKey: 'bukuTamu' },
  INVENTARIS: { id: 'addon_inventaris', name: 'Modul Inventaris - 15k/ bln', priceMonthly: 15000, featureKey: 'inventaris' },
  AI_AGENT: { id: 'addon_ai_agent', name: 'AI Agent (Asisten 24/7) - 59k/ bln', priceMonthly: 59000, featureKey: 'aiAgent' },
  GRUP_CHAT: { id: 'addon_grup_chat', name: 'Grup Chat Warga - 25k/ bln', priceMonthly: 25000, featureKey: 'grupChat' },
  KELUHAN: { id: 'addon_keluhan', name: 'Lapor Keluhan (Warga)', priceMonthly: 0, featureKey: 'complaint' },
};
